# Generated by Django 5.2.18 on 2026-10-08 17:21

import django.core.validators
import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='nom complet')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=160, verbose_name='motif')),
                ('preferred_at', models.DateTimeField(verbose_name='date souhaitée')),
                ('details', models.TextField(blank=True, max_length=2000, verbose_name='précisions')),
                ('status', models.CharField(choices=[('pending', 'À confirmer'), ('confirmed', 'Confirmé'), ('declined', 'Non retenu')], default='pending', max_length=12, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='demandé le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='portal.clientprofile', verbose_name='client')),
            ],
            options={
                'verbose_name': 'demande de rendez-vous',
                'verbose_name_plural': 'demandes de rendez-vous',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='référence')),
                ('title', models.CharField(max_length=180, verbose_name='intitulé du dossier')),
                ('category', models.CharField(choices=[('business', 'Droit des affaires'), ('employment', 'Droit du travail'), ('criminal', 'Droit pénal'), ('family', 'Famille et personnes'), ('property', 'Foncier et immobilier'), ('administrative', 'Droit administratif'), ('other', 'Autre')], default='other', max_length=24, verbose_name='domaine')),
                ('status', models.CharField(choices=[('open', 'En cours'), ('waiting', 'En attente'), ('closed', 'Clôturé')], default='open', max_length=12, verbose_name='statut')),
                ('court', models.CharField(blank=True, max_length=160, verbose_name='juridiction')),
                ('responsible_lawyer', models.CharField(blank=True, max_length=160, verbose_name='avocat responsable')),
                ('opened_at', models.DateField(auto_now_add=True, verbose_name='ouvert le')),
                ('next_hearing', models.DateTimeField(blank=True, null=True, verbose_name='prochaine audience')),
                ('summary', models.TextField(blank=True, verbose_name='résumé')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matters', to='portal.clientprofile', verbose_name='client')),
            ],
            options={
                'verbose_name': 'dossier',
                'verbose_name_plural': 'dossiers',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_client', models.BooleanField(default=False, verbose_name='envoyé par le client')),
                ('content', models.TextField(max_length=5000, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='envoyé le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matter_messages', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portal.matter', verbose_name='dossier')),
            ],
            options={
                'verbose_name': 'message de dossier',
                'verbose_name_plural': 'messages de dossier',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('body', models.TextField(verbose_name='détail')),
                ('visible_to_client', models.BooleanField(default=True, verbose_name='visible par le client')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='portal.matter', verbose_name='dossier')),
            ],
            options={
                'verbose_name': 'événement du dossier',
                'verbose_name_plural': 'événements du dossier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='nom du document')),
                ('file', models.FileField(upload_to=portal.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), portal.models.validate_document_size], verbose_name='fichier privé')),
                ('visible_to_client', models.BooleanField(default=True, verbose_name='visible par le client')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='déposé le')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.matter', verbose_name='dossier')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document privé',
                'verbose_name_plural': 'documents privés',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
