# Generated by Django 5.2.18 on 2026-10-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(help_text='Utilisez une URL HTTPS ou un chemin /static/images/... du site.', max_length=500, verbose_name="URL HTTPS de l'image")),
                ('caption_fr', models.CharField(max_length=160, verbose_name='légende (français)')),
                ('caption_ar', models.CharField(blank=True, max_length=160, verbose_name='légende (arabe)')),
                ('caption_en', models.CharField(blank=True, max_length=160, verbose_name='légende (anglais)')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('is_slide', models.BooleanField(default=False, verbose_name='utiliser dans le diaporama')),
                ('is_active', models.BooleanField(default=True, verbose_name='publiée')),
            ],
            options={
                'verbose_name': 'photo de la galerie',
                'verbose_name_plural': 'photos de la galerie',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=120, verbose_name='titre (français)')),
                ('title_ar', models.CharField(blank=True, max_length=120, verbose_name='titre (arabe)')),
                ('title_en', models.CharField(blank=True, max_length=120, verbose_name='titre (anglais)')),
                ('description_fr', models.TextField(verbose_name='description (français)')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (arabe)')),
                ('description_en', models.TextField(blank=True, verbose_name='description (anglais)')),
                ('icon', models.PositiveSmallIntegerField(choices=[(1, 'Symbole 1'), (2, 'Symbole 2'), (3, 'Symbole 3'), (4, 'Symbole 4'), (5, 'Symbole 5'), (6, 'Symbole 6')], default=1, verbose_name='icône')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='publiée')),
            ],
            options={
                'verbose_name': 'expertise',
                'verbose_name_plural': 'expertises',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_fr', models.CharField(max_length=100, verbose_name='rubrique (français)')),
                ('category_ar', models.CharField(blank=True, max_length=100, verbose_name='rubrique (arabe)')),
                ('category_en', models.CharField(blank=True, max_length=100, verbose_name='rubrique (anglais)')),
                ('title_fr', models.CharField(max_length=200, verbose_name='titre (français)')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='titre (arabe)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='titre (anglais)')),
                ('excerpt_fr', models.TextField(verbose_name='résumé (français)')),
                ('excerpt_ar', models.TextField(blank=True, verbose_name='résumé (arabe)')),
                ('excerpt_en', models.TextField(blank=True, verbose_name='résumé (anglais)')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='date de publication')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='publiée')),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'ordering': ['position', '-published_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Contenus éditoriaux du site public, en français, arabe et anglais.', verbose_name='textes du site par langue')),
                ('telephone', models.CharField(blank=True, max_length=40, verbose_name='téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp')),
                ('telephone_fixe', models.CharField(blank=True, max_length=80, verbose_name='téléphone fixe')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('site_web', models.CharField(blank=True, max_length=160, verbose_name='site internet')),
                ('adresse', models.CharField(blank=True, max_length=240, verbose_name='adresse')),
                ('heures', models.CharField(blank=True, max_length=180, verbose_name='horaires')),
                ('adresse_carte', models.CharField(blank=True, max_length=240, verbose_name='adresse de recherche sur la carte')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
            ],
            options={
                'verbose_name': 'réglages du site',
                'verbose_name_plural': 'réglages du site',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=160, verbose_name='nom (français)')),
                ('name_ar', models.CharField(blank=True, max_length=160, verbose_name='nom (arabe)')),
                ('name_en', models.CharField(blank=True, max_length=160, verbose_name='nom (anglais)')),
                ('title_fr', models.CharField(blank=True, max_length=180, verbose_name='titre (français)')),
                ('title_ar', models.CharField(blank=True, max_length=180, verbose_name='titre (arabe)')),
                ('title_en', models.CharField(blank=True, max_length=180, verbose_name='titre (anglais)')),
                ('bio_fr', models.TextField(blank=True, verbose_name='présentation (français)')),
                ('bio_ar', models.TextField(blank=True, verbose_name='présentation (arabe)')),
                ('bio_en', models.TextField(blank=True, verbose_name='présentation (anglais)')),
                ('credentials_fr', models.JSONField(blank=True, default=list, verbose_name='distinctions (français, liste)')),
                ('credentials_ar', models.JSONField(blank=True, default=list, verbose_name='distinctions (arabe, liste)')),
                ('credentials_en', models.JSONField(blank=True, default=list, verbose_name='distinctions (anglais, liste)')),
                ('portrait_url', models.URLField(blank=True, help_text="Facultatif. Laissez vide pour afficher l'identité graphique du cabinet.", max_length=500, verbose_name='URL HTTPS du portrait')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='publié')),
            ],
            options={
                'verbose_name': "membre de l'équipe",
                'verbose_name_plural': 'équipe',
                'ordering': ['position', 'id'],
            },
        ),
    ]
